version: "2.3"

services:
  interface:
    build: .
    command: python3.7 /usr/app/main.py
    runtime: nvidia
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - QT_DEBUG_PLUGINS=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all

